### ISSUE TITLE
Its not working properly (Resolved in New update)

### ISSUE THREAD

**Issue by asif07hossain** [IAmBlackHacker/Facebook-BruteForce#1]

**Comment by sajedrhayel** [comment]
Can it work with python2 it takes alot of time

**Comment by Norwanoo** [comment]
bor i can't open (passwords.txt ) 
Please

**Comment by 1337r00t** [comment]
@asif07hossain @sajedrhayel @Norwanoo : https://github.com/1337r00t/BruteForce-Facebook

**Comment by IAmBlackHacker** [comment]
> bor i can't open (passwords.txt )
> Please

Just Follow the method as described in readme (git clone)

**Comment by IAmBlackHacker** [comment]
> Can it work with python2 it takes alot of time

Use Linux and GPU

**Comment by sannminwin** [comment]
I could manage it running on ubuntu server with pip3 and python3. 
but I stopped at password 1
how would you make it work ?

**Comment by skcisco15** [comment]
Why it's showing wrong password?  And showing the same password for every ID

Pls fix and update. 

Thanks.

**Comment by Escxtt23** [comment]
Working 100% but it takes a lot of time😀👍🔥🔥

**Comment by asif07hossain** [comment]
I forgot my to back up. Can you send me the full zip file of your working
code?

**Comment by dahn1** [comment]
Mengapa kata sndi yg keluar gak ada yg betull. 
?!*&# itu doang yg keluar semua...

**Comment by Kizami95** [comment]
It works but without a result why ? 😠

**Comment by Melhurian** [comment]
same password every time

**Comment by Kizami95** [comment]
The program does not work my brother

**Comment by IAmBlackHacker** [comment]
> Working 100% but it takes a lot of time😀👍🔥🔥

great

**Comment by IAmBlackHacker** [comment]
> It works but without a result why ? 😠

try correctly
