### ISSUE TITLE
Lie

### ISSUE THREAD

**Issue by ah0lx** [IAmBlackHacker/Facebook-BruteForce#10]
The script is not true and it doesnt work i have my account id and i test it with my real password and it doesnt do anything and keep test the other password. 

- [ ] **fuck my lang**

**Comment by IAmBlackHacker** [comment]
Many people use this script and got success...., may there a problem in your way of using this script. There are two scripts, try both.

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help
