### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ManhThangIT** [IAmBlackHacker/Facebook-BruteForce#12]
Hello!
When I run the pass.txt file, it stops when I see the correct password.

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help

**Comment by NyiNyi1996** [comment]
How do you do?

**Comment by skrobin18** [comment]
Do You Know Me?

**Comment by IAmBlackHacker** [comment]
We'll definitely look into this
Thanks,
