### ISSUE TITLE
seriously?

### ISSUE THREAD

**Issue by DamonMerrick** [IAmBlackHacker/Facebook-BruteForce#26]
Is this a  joke?
~!@#$%^&*()_+|
29 :  <><><>
30 :  <>!@#$%^&*()
31 :  <>#&@{
33 :  <{:-|>
36 :  ========
37 :  ==//==
41 :  >>>>>>>>>??
44 :  |(-]||
45 :  |@--@|
50 :  ______
51 :  _______
52 :  ________
53 :  __)(__
55 :  _\'_\'
56 :  _+||+_
60 :  -=-=-=
61 :  -=-=-=-=
63 :  -=[]\\;',./
65 :  -- ---
66 :  --__--
70 :  ------
71 :  -------
72 :  --------
73 :  ---------
74 :  ----------
75 :  --------------------
76 :  ------+
78 :  ---+++***
79 :  --**//++
80 :  -.--.--.-
82 :  -*/-*/-*/
83 :  -*/-*/-*/+
85 :  -+-+-+
89 :  ,,,,,,
90 :  ,;:!,;:!
91 :  ,/,/,/..
94 :  ,.-,.-
95 :  ,.,.,.,.
97 :  ,./<>?
98 :  ,./,./,./
99 :  ,./;'[]\\
102 :  ;;;;;;
103 :  ;;;;;;;;
104 :  ;;;\\\';;;
107 :  :.:.:.:.
109 :  :@~<>?
111 :  !^)!!$%^&
115 :  !!!!!!
116 :  !!!!!!!
117 :  !!!!!!!!
118 :  !!!!!!!!!!
119 :  !!!@@@
120 :  !!!@@@###
122 :  !!@@##
you call this passwords? why not adding an option to choose your own list of passwords? lol

**Comment by rizalli** [comment]
why?i am not seriusly

Pada tanggal 30 Mei 2020 12.31 AM, "DamonMerrick" <notifications@github.com>
menulis:

**Comment by IAmBlackHacker** [comment]
you can definitely  do this
