### ISSUE TITLE
Program randomly fails

### ISSUE THREAD

**Issue by ghost** [IAmBlackHacker/Facebook-BruteForce#27]
I have list with passwords and in it is my password i put my email in it and run it. And it find the password so I go again with different account and it goes though list and doesn't find it so i run it again i it finds password of second account. I have tested this around 20 times with 4 account and it fails around every 8 time.

**Comment by IAmBlackHacker** [comment]
Ok We'll look into this
Thanks

**Comment by IAmBlackHacker** [comment]
Resolved
