### ISSUE TITLE
Wait 7 Hours

### ISSUE THREAD

**Issue by FacebookBruteForce** [IAmBlackHacker/Facebook-BruteForce#29]
wait 7 hours to get those passwords but still didn't get the passwords. you can create a fbpass text file to cracking fb in short time

**Comment by slamichhnetune** [comment]
You can increase the time by importing BeautifulSoup4 instead of BeautifulSoup and do corrections in the  program, more info  [here](https://www.crummy.com/software/BeautifulSoup/bs4/doc/index.html)

**Comment by IAmBlackHacker** [comment]
Thanks
