### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PranayShende** [IAmBlackHacker/Facebook-BruteForce#41]
I make a wordlist with my password in it. Use the wordlist. The tool is trying passwords but when it comes to correct password, it just tries it and jump to next. It doesnt return correct password and didnt break the loop. When the list ends it says password is not in the list.

**Comment by someone38** [comment]
same

**Comment by emailg** [comment]
Same

**Comment by IAmBlackHacker** [comment]
Thanks will look into that
