### ISSUE TITLE
Loop Breaker

### ISSUE THREAD

**Issue by sumeets11** [IAmBlackHacker/Facebook-BruteForce#43]
The line with:
if 'Find Friends' in r.text or 'Two-Factor Authentication Required' in r.text:

It works in Two Way Authorization, but it seems to not work for a successful login. Maybe we can change that Criteria to make it work?
Can you suggest some other phrases instead of "Find Friends'?

**Comment by IAmBlackHacker** [comment]
Thanks for your suggestion, will look into that

**Comment by up2smoke** [comment]
When?
