### ISSUE TITLE
fb warning

### ISSUE THREAD

**Issue by b-Istiak-s** [IAmBlackHacker/Facebook-BruteForce#55]
This source code is working properly. But, I noticed that whenever I hack my account. Facebook is sending me a message that is saying,"We have seen login in your account from unknown place. Please, secure your account". Something just like this. I know that, Facebook is very secure. I don't think that there's possible way to ignore it. Could you work with source code furthermore to remove the security if possible?

**Comment by jitendrapandya1996** [comment]
It's not working after launch

**Comment by dhanushkkarh** [comment]
the password might be stored in a text file if your running on linux
