### ISSUE TITLE
Does Not work: crap 

### ISSUE THREAD

**Issue by AbdelXY** [IAmBlackHacker/Facebook-BruteForce#6]
Dear Team,
Thank you for writing this code.
I have tried your tool but unfortunately, it only stops after reading the 1st password in the txt file. it gives the 1st password as correct which is wrong.
There is an issue with your code.

**Comment by matefs** [comment]
The same to me

**Comment by Melhurian** [comment]
Same to me ! :(

**Comment by IAmBlackHacker** [comment]
ok, I'll check and update it soon ...

**Comment by shifatbuet** [comment]
It doesn't work at all ..


Just delete this garbage repository please...

Its really confuses people....
