### ISSUE TITLE
How many time we need to wait?

### ISSUE THREAD

**Issue by ArtMin96** [IAmBlackHacker/Facebook-BruteForce#8]
How many time we need to wait? I have already 2800 lines. Is this trying to find or just only generating random numbers and strings

**Comment by IAmBlackHacker** [comment]
it's checking each password

**Comment by IAmBlackHacker** [comment]
until get a password!

**Comment by MohammadBinAftab** [comment]
I am trying to brute Force my FB id. My password is mixed of alphabets and numbers. It is 8 character password. How much it takes to brute Force.

**Comment by WAIYANgg** [comment]
5 hours

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help
