### ISSUE TITLE
No password match

### ISSUE THREAD

**Issue by Arcamemoria** [IAmBlackHacker/Facebook-BruteForce#81]
I consciously put my password into the 10 first password of the list but the script doesnt stop on it. For now that didnt work for me.

**Comment by dhanushkkarh** [comment]
you can fork the repository and edit the password.txt file.
Alternatively, you can use ```
nano passwords.txt
``` in your kali linux. It'll open up a text editor. Hope this helps 😉

**Comment by IAmBlackHacker** [comment]
try a week later
