### ISSUE TITLE
Even with write password, Doesn't work 

### ISSUE THREAD

**Issue by UNITY002** [IAmBlackHacker/Facebook-BruteForce#83]
Even with write password, Doesn't work

**Comment by IAmBlackHacker** [comment]
will not work on 2fa account

**Comment by UNITY002** [comment]
Thanks for your reply, but I checked there was no any kind of 2fa auth or any kind either 
So, I think you should try it out for yourself now

**Comment by IAmBlackHacker** [comment]
Sure will check

**Comment by Caferoma** [comment]
Yes, I am a member with you on github
Thank you for your kind reply

I apologize for the delay in responding, I was very busy with how to use
the hack tools, but I have not succeeded in that for two months, and I want
to hack Facebook, but I was not able to cause me great frustration
😢😢😢😢😢😢

**Comment by Caferoma** [comment]
Yes, I am a member with you on github
Thank you for your kind reply

I apologize for the delay in responding, I was very busy with how to use
the hack tools, but I have not succeeded in that for two months, and I want
to hack Facebook, but I was not able to cause me great frustration
😢😢😢😢😢😢

**Comment by IAmBlackHacker** [comment]
Haha, this script was written in 2018
Definitely you can try out for some other alternatives
